<?php $this->layout()->setLayout('layout_fo_ehcg'); ?>

<!--data table-->
<script src="<?= $this->baseUrl('resources_fo_ehcg/js/jquery.dataTables.js'); ?>"></script>
<script src="<?= $this->baseUrl('resources_fo_ehcg/js/dataTables.tableTools.js'); ?>"></script>
<script src="<?= $this->baseUrl('resources_fo_ehcg/js/jquery.dataTables.bootstrap.js'); ?>"></script>

<!-- Data table-->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('resources_fo_ehcg/css/libs/dataTables.fixedHeader.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('resources_fo_ehcg/css/libs/dataTables.tableTools.css'); ?>">
<div class="row">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<header class="main-box-header clearfix">
				<!-- Breadcumbs -->
				<div class="row">
					<div class="col-md-6">
						<ul id="breadcrumbs-two">
							<li><a style="cursor: pointer;">
									<i class="fa fa-home"></i>
									Tableau de bord</a></li>

							<li><a class="current" style="cursor: pointer;">
									<i class="fa fa-files-o"></i>
									Cuisine</a></li>

						</ul>
					</div>
					<div class="col-md-6">
						<div class="pull-right">
							<ul>
								<li id="notif" class="dropdown hidden-xs"></li>
							</ul>

						</div>
					</div>
				</div>
			</header>
			<div class="main-box-body clearfix">
				<div class="col-md-12">
					<div class="table-responsive" style="overflow: hidden;">
						<table id="jobs-table" class="table table-hover user-list">
							<thead>
							<tr>
								<th>CLIENT</th>
								<th>TITRE DEMANDE</th>
								<th>Publié Le</th>
								<th>DATE CREATION</th>
								<th>PUBLIE PAR</th>
								<th>PUBLIER EN LIGNE</th>
								<th>PRIX</th>
								<th>CATEGORIE</th>
								<th>VILLE</th>
								<th>CODE POSTAL</th>
								<th>ACTION</th>
							</tr>
							</thead>
							<tbody>
							<?php foreach ($this->demandes as $demande): ?>
								<tr class="job-link" data-url="/auth/cuisine/edit/id/<?= $demande['id_demande']; ?>">
									<td>
										<a class="user-link" id="title-client-<?= $demande['id_demande']; ?>" style="cursor: pointer; margin-left: 0; padding-top: 0">
											<?= $demande['nom_particulier'] ?>
											<?= $demande['prenom_particulier']; ?>
										</a>
									</td>
									<td>
										<?= $demande['titre_demande']; ?>
									</td>
									<td>
										<?= date('d/m/Y', strtotime($demande['date_publication'])) ?>
									</td>
									<td>
										<?= date('d/m/Y', strtotime($demande['date_creation'])) ?>
									</td>
									<td>
										<?= $demande['lastname_user'] . ' ' . $demande['firstname_user']; ?>
									</td>

									<td>
										<?= $demande['publier_en_ligne'] === '1' ? 'Oui' : 'Non'; ?>
									</td>
									<td>
										<?= $demande['prix_mise_en_ligne'] ?>
									</td>
									<td>
										<?= $demande['categorie'] ?>
									</td>
									<td>
										<?= $demande['ville'] ?>
									</td>
									<td>
										<?= $demande['code_postal'] ?>
									</td>
									<td><a class="table-link" id="btn-edit-client-<?= $demande['id_demande'] ?>" style="cursor: pointer;">
											<span class="fa-stack">
												<i class="fa fa-square fa-stack-2x"></i>
												<i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
											</span>
										</a>
									</td>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>

	// Long polling notification data
	function getNotifications(lastCount=-1) {
		$.ajax({
			url: '/auth/cuisine/notification?count=' + lastCount,
			dataType: 'json',
			async: true,
			cache: false,
			timeout: 50000,
			success: function (data) {
				if (data.html) {
					lastCount = data.count;
					$('#notif').html(data.html);
				}
			},
			complete: function () {

				// wait before you retry
				setTimeout(function () {
					getNotifications(lastCount)
				}, 5000);
			}
		});
	}


	$(function () {

		// Loading notifications
		getNotifications();


		// DataTable setup
		$('#jobs-table').dataTable({
			'info': false,
			'oLanguage': {
				sProcessing: '<i style="font-size:50px;color:#6A6E9B" class="fa fa-spinner fa-spin"></i> Chargement en cours ...'
			},
			"jQueryUI": true,
			'sDom': 'lTfr<"clearfix">tip',
			'oTableTools': {
				'aButtons': []
			},
			"paging": false,
			"ordering": true,
			"processing": true,
			"searching": true
		});

		$('.job-link').on('click', function (e) {
			e.preventDefault();
			const url = $(this).data('url');
			$('#Content').html('<div style="text-align: center"><i style="font-size:50px;color:#6A6E9B" class="fa fa-spinner fa-spin"></i> Chargement en cours ...veuillez patientez</div>');

			$.get(url, function (data) {
				$('#Content').html(data)
			})
		})
	});

</script>