<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Auth_Model_ArtisanProxy extends \Auth_Model_Artisan implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function hasActivite($id)
    {
        $this->__load();
        return parent::hasActivite($id);
    }

    public function addActivite(\Auth_Model_Activite $activite)
    {
        $this->__load();
        return parent::addActivite($activite);
    }

    public function __set($attr, $val)
    {
        $this->__load();
        return parent::__set($attr, $val);
    }

    public function __get($attr)
    {
        $this->__load();
        return parent::__get($attr);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getId_artisan()
    {
        $this->__load();
        return parent::getId_artisan();
    }

    public function getId_chantier()
    {
        $this->__load();
        return parent::getId_chantier();
    }

    public function getChantier()
    {
        $this->__load();
        return parent::getChantier();
    }

    public function getCode_artisan()
    {
        $this->__load();
        return parent::getCode_artisan();
    }

    public function getNom_artisan()
    {
        $this->__load();
        return parent::getNom_artisan();
    }

    public function getPrenom_artisan()
    {
        $this->__load();
        return parent::getPrenom_artisan();
    }

    public function getRaison_sociale()
    {
        $this->__load();
        return parent::getRaison_sociale();
    }

    public function getEmail_artisan()
    {
        $this->__load();
        return parent::getEmail_artisan();
    }

    public function getTelephone_fixe()
    {
        $this->__load();
        return parent::getTelephone_fixe();
    }

    public function getTelephone_portable()
    {
        $this->__load();
        return parent::getTelephone_portable();
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function getRcs()
    {
        $this->__load();
        return parent::getRcs();
    }

    public function getSiret()
    {
        $this->__load();
        return parent::getSiret();
    }

    public function getCode_NAF()
    {
        $this->__load();
        return parent::getCode_NAF();
    }

    public function getHoraireRDV()
    {
        $this->__load();
        return parent::getHoraireRDV();
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function getPass()
    {
        $this->__load();
        return parent::getPass();
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function getQualification()
    {
        $this->__load();
        return parent::getQualification();
    }

    public function setId_artisan($id_artisan)
    {
        $this->__load();
        return parent::setId_artisan($id_artisan);
    }

    public function setId_chantier($id_chantier)
    {
        $this->__load();
        return parent::setId_chantier($id_chantier);
    }

    public function setChantier($chantier)
    {
        $this->__load();
        return parent::setChantier($chantier);
    }

    public function setCode_artisan($code_artisan)
    {
        $this->__load();
        return parent::setCode_artisan($code_artisan);
    }

    public function setNom_artisan($nom_artisan)
    {
        $this->__load();
        return parent::setNom_artisan($nom_artisan);
    }

    public function setPrenom_artisan($prenom_artisan)
    {
        $this->__load();
        return parent::setPrenom_artisan($prenom_artisan);
    }

    public function setRaison_sociale($raison_sociale)
    {
        $this->__load();
        return parent::setRaison_sociale($raison_sociale);
    }

    public function setEmail_artisan($email_artisan)
    {
        $this->__load();
        return parent::setEmail_artisan($email_artisan);
    }

    public function setTelephone_fixe($telephone_fixe)
    {
        $this->__load();
        return parent::setTelephone_fixe($telephone_fixe);
    }

    public function setTelephone_portable($telephone_portable)
    {
        $this->__load();
        return parent::setTelephone_portable($telephone_portable);
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function setPass($pass)
    {
        $this->__load();
        return parent::setPass($pass);
    }

    public function setRcs($rcs)
    {
        $this->__load();
        return parent::setRcs($rcs);
    }

    public function setSiret($siret)
    {
        $this->__load();
        return parent::setSiret($siret);
    }

    public function setCode_NAF($code_NAF)
    {
        $this->__load();
        return parent::setCode_NAF($code_NAF);
    }

    public function setHoraireRDV($horaireRDV)
    {
        $this->__load();
        return parent::setHoraireRDV($horaireRDV);
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function setQualification($qualification)
    {
        $this->__load();
        return parent::setQualification($qualification);
    }

    public function getSpecialities()
    {
        $this->__load();
        return parent::getSpecialities();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_artisan', 'id_chantier', 'chantier', 'code_artisan', 'nom_artisan', 'prenom_artisan', 'raison_sociale', 'email_artisan', 'telephone_fixe', 'telephone_portable', 'fax', 'rcs', 'siret', 'code_NAF', 'horaireRDV', 'description', 'pass', 'login', 'qualification', 'activites', 'demandes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}