<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Auth_Model_ParticulierProxy extends \Auth_Model_Particulier implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __set($attr, $val)
    {
        $this->__load();
        return parent::__set($attr, $val);
    }

    public function __get($attr)
    {
        $this->__load();
        return parent::__get($attr);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getId_particulier()
    {
        $this->__load();
        return parent::getId_particulier();
    }

    public function getNom_particulier()
    {
        $this->__load();
        return parent::getNom_particulier();
    }

    public function getPrenom_particulier()
    {
        $this->__load();
        return parent::getPrenom_particulier();
    }

    public function getTelephone_fixe()
    {
        $this->__load();
        return parent::getTelephone_fixe();
    }

    public function getTelephone_portable()
    {
        $this->__load();
        return parent::getTelephone_portable();
    }

    public function getCivilite()
    {
        $this->__load();
        return parent::getCivilite();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getHoraireRDV()
    {
        $this->__load();
        return parent::getHoraireRDV();
    }

    public function setId_particulier($id_particulier)
    {
        $this->__load();
        return parent::setId_particulier($id_particulier);
    }

    public function setNom_particulier($nom_particulier)
    {
        $this->__load();
        return parent::setNom_particulier($nom_particulier);
    }

    public function setPrenom_particulier($prenom_particulier)
    {
        $this->__load();
        return parent::setPrenom_particulier($prenom_particulier);
    }

    public function setTelephone_fixe($telephone_fixe)
    {
        $this->__load();
        return parent::setTelephone_fixe($telephone_fixe);
    }

    public function setTelephone_portable($telephone_portable)
    {
        $this->__load();
        return parent::setTelephone_portable($telephone_portable);
    }

    public function setCivilite($civilite)
    {
        $this->__load();
        return parent::setCivilite($civilite);
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function setHoraireRDV($horaireRDV)
    {
        $this->__load();
        return parent::setHoraireRDV($horaireRDV);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_particulier', 'nom_particulier', 'prenom_particulier', 'telephone_fixe', 'telephone_portable', 'civilite', 'email', 'horaireRDV');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}