<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Auth_Model_DepartementProxy extends \Auth_Model_Departement implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function addArtisan(\Auth_Model_Artisan $artisan)
    {
        $this->__load();
        return parent::addArtisan($artisan);
    }

    public function removeArtisan(\Auth_Model_Artisan $artisan)
    {
        $this->__load();
        return parent::removeArtisan($artisan);
    }

    public function __set($attr, $val)
    {
        $this->__load();
        return parent::__set($attr, $val);
    }

    public function __get($attr)
    {
        $this->__load();
        return parent::__get($attr);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getCode_departement()
    {
        $this->__load();
        return parent::getCode_departement();
    }

    public function getNom_departement()
    {
        $this->__load();
        return parent::getNom_departement();
    }

    public function setCode_departement($code_departement)
    {
        $this->__load();
        return parent::setCode_departement($code_departement);
    }

    public function setNom_departement($nom_departement)
    {
        $this->__load();
        return parent::setNom_departement($nom_departement);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'code_departement', 'nom_departement', 'artisans', 'zones');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}