<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Auth_Model_DemandedevisProxy extends \Auth_Model_Demandedevis implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __set($attr, $val)
    {
        $this->__load();
        return parent::__set($attr, $val);
    }

    public function __get($attr)
    {
        $this->__load();
        return parent::__get($attr);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getId_demande()
    {
        $this->__load();
        return parent::getId_demande();
    }

    public function getTitre_demande()
    {
        $this->__load();
        return parent::getTitre_demande();
    }

    public function getDelai_souhaite()
    {
        $this->__load();
        return parent::getDelai_souhaite();
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function getType_demandeur()
    {
        $this->__load();
        return parent::getType_demandeur();
    }

    public function getType_propriete()
    {
        $this->__load();
        return parent::getType_propriete();
    }

    public function getType_batiment()
    {
        $this->__load();
        return parent::getType_batiment();
    }

    public function getBudget_approximatif()
    {
        $this->__load();
        return parent::getBudget_approximatif();
    }

    public function getFinancement_projet()
    {
        $this->__load();
        return parent::getFinancement_projet();
    }

    public function getObjectif_demande()
    {
        $this->__load();
        return parent::getObjectif_demande();
    }

    public function getPrestation_souhaite()
    {
        $this->__load();
        return parent::getPrestation_souhaite();
    }

    public function getIndication_complementaire()
    {
        $this->__load();
        return parent::getIndication_complementaire();
    }

    public function getQualification()
    {
        $this->__load();
        return parent::getQualification();
    }

    public function getPrix_mise_en_ligne()
    {
        $this->__load();
        return parent::getPrix_mise_en_ligne();
    }

    public function getPrix_promo()
    {
        $this->__load();
        return parent::getPrix_promo();
    }

    public function getPublier_en_ligne()
    {
        $this->__load();
        return parent::getPublier_en_ligne();
    }

    public function getPublier_envoi()
    {
        $this->__load();
        return parent::getPublier_envoi();
    }

    public function getChemin_pdf()
    {
        $this->__load();
        return parent::getChemin_pdf();
    }

    public function getDate_creation()
    {
        $this->__load();
        return parent::getDate_creation();
    }

    public function getDate_publication()
    {
        $this->__load();
        return parent::getDate_publication();
    }

    public function getId_particulier()
    {
        $this->__load();
        return parent::getId_particulier();
    }

    public function getId_activite()
    {
        $this->__load();
        return parent::getId_activite();
    }

    public function getId_chantier()
    {
        $this->__load();
        return parent::getId_chantier();
    }

    public function getId_user()
    {
        $this->__load();
        return parent::getId_user();
    }

    public function getVendu()
    {
        $this->__load();
        return parent::getVendu();
    }

    public function setId_demande($id_demande)
    {
        $this->__load();
        return parent::setId_demande($id_demande);
    }

    public function setTitre_demande($titre_demande)
    {
        $this->__load();
        return parent::setTitre_demande($titre_demande);
    }

    public function setDelai_souhaite($delai_souhaite)
    {
        $this->__load();
        return parent::setDelai_souhaite($delai_souhaite);
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function setType_demandeur($type_demandeur)
    {
        $this->__load();
        return parent::setType_demandeur($type_demandeur);
    }

    public function setType_propriete($type_propriete)
    {
        $this->__load();
        return parent::setType_propriete($type_propriete);
    }

    public function setType_batiment($type_batiment)
    {
        $this->__load();
        return parent::setType_batiment($type_batiment);
    }

    public function setBudget_approximatif($budget_approximatif)
    {
        $this->__load();
        return parent::setBudget_approximatif($budget_approximatif);
    }

    public function setFinancement_projet($financement_projet)
    {
        $this->__load();
        return parent::setFinancement_projet($financement_projet);
    }

    public function setObjectif_demande($objectif_demande)
    {
        $this->__load();
        return parent::setObjectif_demande($objectif_demande);
    }

    public function setPrestation_souhaite($prestation_souhaite)
    {
        $this->__load();
        return parent::setPrestation_souhaite($prestation_souhaite);
    }

    public function setIndication_complementaire($indication_complementaire)
    {
        $this->__load();
        return parent::setIndication_complementaire($indication_complementaire);
    }

    public function setQualification($qualification)
    {
        $this->__load();
        return parent::setQualification($qualification);
    }

    public function setPrix_mise_en_ligne($prix_mise_en_ligne)
    {
        $this->__load();
        return parent::setPrix_mise_en_ligne($prix_mise_en_ligne);
    }

    public function setPrix_promo($prix_promo)
    {
        $this->__load();
        return parent::setPrix_promo($prix_promo);
    }

    public function setPublier_en_ligne($publier_en_ligne)
    {
        $this->__load();
        return parent::setPublier_en_ligne($publier_en_ligne);
    }

    public function setPublier_envoi($publier_envoi)
    {
        $this->__load();
        return parent::setPublier_envoi($publier_envoi);
    }

    public function setChemin_pdf($chemin_pdf)
    {
        $this->__load();
        return parent::setChemin_pdf($chemin_pdf);
    }

    public function setDate_creation($date_creation)
    {
        $this->__load();
        return parent::setDate_creation($date_creation);
    }

    public function setDate_publication($date_publication)
    {
        $this->__load();
        return parent::setDate_publication($date_publication);
    }

    public function setId_particulier($id_particulier)
    {
        $this->__load();
        return parent::setId_particulier($id_particulier);
    }

    public function setId_activite($id_activite)
    {
        $this->__load();
        return parent::setId_activite($id_activite);
    }

    public function setId_chantier($id_chantier)
    {
        $this->__load();
        return parent::setId_chantier($id_chantier);
    }

    public function setId_user($id_user)
    {
        $this->__load();
        return parent::setId_user($id_user);
    }

    public function setVendu($vendu)
    {
        $this->__load();
        return parent::setVendu($vendu);
    }

    public function getUrl()
    {
        $this->__load();
        return parent::getUrl();
    }

    public function getRef()
    {
        $this->__load();
        return parent::getRef();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_demande', 'titre_demande', 'delai_souhaite', 'description', 'type_demandeur', 'type_propriete', 'type_batiment', 'budget_approximatif', 'financement_projet', 'objectif_demande', 'prestation_souhaite', 'indication_complementaire', 'qualification', 'prix_mise_en_ligne', 'prix_promo', 'publier_en_ligne', 'publier_envoi', 'chemin_pdf', 'date_creation', 'date_publication', 'id_particulier', 'id_activite', 'id_chantier', 'id_user', 'vendu', 'acheteurs');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}