<div style="width: 650px; margin: 80px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center;">Votre mot de passe a été réinitialisé</h1>
	<p>Bonjour <?= $this->name ?>,</p>
	<p>Vous pouvez vous connecter temporairement avec ce nouveau mot de passe:</p>
	<h1>Mot de passe: <?= $this->password; ?></h1>
	<p> Pensez à le changer dans votre plateforme</p>
	<p>L'équipe <a href="http://mister-devis.com">mister-devis.com</a></p>
</div>