<div style="width: 650px; margin: 80px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center;">Une nouvelle demande de devis a été mise en ligne</h1>
	<p>Bonjour <?= $this->nom ?>,</p>
	<p>Nous vous informons qu'une nouvelle demande de devis concernant votre activité et votre zone d'intervention a été publiée dans la plateforme.</p>
	<p>Vous pouvez la consulter dans votre espace pro.</p>
	<h1>Demande N°: <?= $this->ref; ?></h1>
	<p> A très bientôt</p>
	<p>L'équipe <a href="http://mister-devis.com">mister-devis.com</a></p>
</div>