<div style="width: 650px; margin: 80px auto;">
	<div style="text-align: center; padding: 10px;"><img src="https://www.mister-devis.com/wp-content/uploads/2017/03/logo_mister_devis-1.png" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center;">Confirmation de votre demande de devis</h1>
	<p>Bonjour <?= $this->nom ?>,</p>
	<p>Nous vous confirmons la réception de votre demande de devis.</p>
	<p>Prochainement un de nos conseillers vous contactera afin de recueillir l'ensemble des informations concernant votre projet.</p>
	<h1>Demande N°: <?= $this->ref; ?></h1>
	<p> A très bientôt</p>
	<p>L'équipe <a href="http://mister-devis.com">mister-devis.com</a></p>
</div>