<div style="width: 650px; margin: 80px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center;">Un professionnel est intéressé par votre demande</h1>
	<p>Bonjour <?= $this->particulier->prenom_particulier . ' ' . $this->particulier->nom_particulier ?>,</p>
	<p>Nous vous informons qu'un professionnel est intéressé par votre demande
		de devis et il vous contactera très rapidement.</p>
	<p>Voici ses coordonnées postales et téléphoniques qui vous permettrons de
		le joindre avant son appel :</p>
	<ul>
		<li>Nom : <?= $this->artisan->nom_artisan ?></li>
		<li>Prénom : <?= $this->artisan->prenom_artisan ?></li>
		<li>Société : <?= $this->artisan->raison_sociale ?></li>
		<li>Adresse : <?= $this->artisan->getAdresse() ?></li>
		<li>Ville : <?= $this->artisan->ville ?></li>
		<li>Code Postal : <?= $this->artisan->code_postal ?></li>
		<li>Téléphone : <?= $this->artisan->telephone_portable ?></li>
		<li>E-mail : <?= $this->artisan->email_artisan ?></li>
	</ul>
	<p>Cordialement</p>
	<p>L'équipe <a href="http://www.mister-devis.com">mister-devis.com</a></p>
</div>