<div class="listAllViewsUser responsive-table-on" id="listUser">
	<div class="with-padding">
		<div class="mid-margin-bottom compact">	
	        	<span class="button-group" style="margin-top:5px;">
	        		<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'view')){ ?>
	            		<a title="Liste des utilisateurs" class="button silver-gradient showUser disabled" >Utilisateur</a>
	            	<?php }?>	
	            	<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'add')){ ?>
	                <a class="button silver-gradient cursor-pointer mtCreate " title="Créer un utilisateur" href="<?=$this->baseUrl('/auth/user/add')?>">
	                            Créer un utilisateur
	                </a> 
	                <?php }?>	
	        	</span>
		
	        	<span class="button-group" style="margin-top:5px;">
	        	<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'view')){ ?>
                	<a title="Liste des groupes d'utilisateur" class="button silver-gradient cursor-pointer showGroup" >Groupes</a>
                <?php }?>
                <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'add')){ ?>
                    <a class="button silver-gradient cursor-pointer mtCreate " title="Créer un groupe" href="<?=$this->baseUrl('/auth/usergroup/add')?>">
                            Créer un groupe
                    </a>  
                 <?php }?>
	        	</span>
	
		</div>
	    	<table class="table" id="tabUser">
				<thead>
					<tr>
						<th class="checkbox-cell hide-on-mobile" scope="col"><input type="checkbox" value="1" id="check-all" name="check-all"></th>	
						<th scope="col" class="hidden">Nom cleared</th>
						<th scope="col">Nom</th>
						<th scope="col">Prénom</th>
						<th class="hide-on-mobile" scope="col">Télephone</th>
						<th width="1%" class="hide-on-mobile-portrait"  scope="col">Email</th>
						<th width="5%" class="hide-on-mobile" scope="col">Groupe</th>
						<th class="hide-on-tablet" width="1%" scope="col">Statut</th>
						<th class="align-center tiny-cell" scope="col">Actions</th>
					</tr>				
				</thead>	
				<tbody></tbody>
				<tfoot>
					<tr>
						<td colspan="9">
							<div id="resultQueryUser"></div>
						</td>
					</tr>
				</tfoot>
			</table>
			<div style="margin:auto;width:100px" id="loadingUser"><img src="img/standard/loaders/loading32.gif" /></div>
			<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'delete')|| Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'edit')){ ?>
            
            <div class="table-footer silver-gradient button-height large-margin-bottom" id="user_applyToSelection">
                 <div class="float-right">
                    <!--div id="" class="button-group paginationFirst"></div-->
                    <div id="Pagination"class="button-group userPagination"></div>
                    <!--div id="" class="button-group paginationLast"></div-->
                </div>
                <div class="hide-on-mobile" style="width:280px;">
                     <select name="select90" id="selectedActionUser"  class="select silver-gradient cursor-default">
                        <option value="">Appliquer à la selection</option>
                        <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'delete')){ ?>
                            <option value="delete">Supprimer</option>
                        <?php }?>
                        <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'edit')){ ?>
                            <option value="disable">Désactiver</option>
                            <option value="enable">Activer</option>
                        <?php }?>
                     </select><button class="button silver-gradient actionUser tiny-margin-left" type="submit">Valider</button>
                 </div>
			</div>
            
		<?php }?>
	</div>
</div>	


<div class="listAllViewsUser hide responsive-table-on" id="listGroup">
	<div class="with-padding">
		<div class="mid-margin-bottom compact">
				
            <span class="button-group" style="margin-top:5px;">
                <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'view')){ ?>
                    <a title="Liste des utilisateurs" class="button silver-gradient showUser disabled" >Utilisateur</a>
                <?php }?>	
                <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'add')){ ?>
                <a class="button silver-gradient cursor-pointer mtCreate " title="Créer un utilisateur" href="<?=$this->baseUrl('/auth/user/add')?>">
                            Créer un utilisateur
                </a> 
                <?php }?>	
            </span>
    
            <span class="button-group" style="margin-top:5px;">
            <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'view')){ ?>
                <a title="Liste des groupes d'utilisateur" class="button silver-gradient cursor-pointer showGroup" >Groupes</a>
            <?php }?>
            <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'add')){ ?>
                <a class="button silver-gradient cursor-pointer mtCreate " title="Créer un groupe" href="<?=$this->baseUrl('/auth/usergroup/add')?>">
                        Créer un groupe
                </a>  
             <?php }?>
            </span>
		
		</div>
	       <table class="table responsive-table" id="tabUsergroup">
				<thead>
					<tr>
						<th class="checkbox-cell hide-on-mobile"><input type="checkbox" value="1" id="check-all" name="check-all"></th>	
						<th class="uppercase">Groupe</th>
						<th class="hide-on-mobile-portrait" width="1%">Statut</th>
						<!--th class="hide-on-mobile hide-on-tablet">Création</th-->
						<th class="align-center tiny-cell" scope="col">Actions</th>
					</tr>				
				</thead>	
				<tbody></tbody>
				<tfoot>
					<tr>
						<td colspan="5">
							<div id="resultQueryGroup"></div>
						</td>
					</tr>
				</tfoot>
	       </table>
	       <div style="margin:auto;width:100px" id="loadingUsergroup"><img src="img/standard/loaders/loading32.gif" /></div>
	        <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'delete')|| Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'edit')){ ?>
				<div class="table-footer silver-gradient button-height large-margin-bottom" id="usergroup_applyToSelection">
		           <div class="float-right">
		           		<!--div id="" class="button-group paginationFirst" ></div-->
				    	<div id="Pagination"class="button-group groupPagination"></div>
				    	<!--div id="" class="button-group paginationLast" ></div-->
				    </div>
                	<div class="hide-on-mobile" style="width:280px;">
                        <select name="select90" id="selectedActionUsergroup" class="select silver-gradient cursor-default">
                            <option value="">Appliquer à la selection</option>
                             <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'delete')){ ?>
                                <option value="delete">Supprimer</option>
                            <?php }?>
                            <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'edit')){ ?>
                                <option value="disable">Désactiver</option>
                                <option value="enable">Activer</option>
                            <?php }?><button class="button silver-gradient actionGroup tinu-margin-left" type="submit">Valider</button>
                       </select><button class="button silver-gradient actionUsergroup tiny-margin-left" type="submit">Valider</button>
                   </div>
			  </div>
		  <?php }?>
	</div>
</div>	

<!------------------------ User Template ------------------------->

<script id="userClone" type="text/template">
				<tr class="listenerCheckbox">
					<th scope="row" class="checkbox-cell hide-on-mobile"><span class="hidden">${user.iduser}</span><input type="checkbox" class="userid" name="checked[]" id="check-${user.iduser}" value="${user.iduser}"></th>
					<td class="namecleared prop hidden" entity="namecleared"> ${stripAccents(user.lastnameuser)} ${stripAccents(user.firstnameuser)}</td>
					<td class="firstnameuser prop" entity="lastnameuser">${user.lastnameuser}</td>
					<td class="prop" entity="firstnameuser">${user.firstnameuser}</td>
					{{if user.mobileuser == "" }}
						<td class="usertel hide-on-mobile prop" entity="phoneuser">${user.phoneuser}</td>	
					{{else}}
						<td class="usertel hide-on-mobile prop" entity="mobileuser">${user.mobileuser}</td>	
					{{/if}}
					<td class="hide-on-mobile prop" entity="emailuser">${user.emailuser}</td>
					<td class="hide-on-mobile prop" entity="namegroup">${group.namegroup}</td>
					{{if user.statususer == true }}
						<td class="statusUser hide-on-tablet prop" entity="statususer"><small class="tag">Actif</small></td>	
					{{else}}
						<td class="statusUser hide-on-tablet prop " entity="statususer"><small class="tag red-bg">Inactif</small></td>	
					{{/if}}
					<td class="low-padding align-center tiny-cell border-right-action">
		                 <span class="button-group compact">
		                 		<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'edit')){ ?>
		             		    	<a class="mtCreate button icon-pencil" title="Editer l'utilisateur" href="<?= $this->baseUrl("/auth/user/update/id/") ?>${user.iduser}"></a>
		             		   <?php }?>
		                      <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'delete')){ ?>
		                       	<a class="button icon-cross blue-gradient delUser" title="Supprimer l'utilisateur" href="#" rel="${user.iduser}"></a>
		                       <?php }?>
		                 </span>
		             </td>
				</tr>
</script>

<script id="userActionClone" type="text/template">
	<div>
		<span class="button-group compact ">
			<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'edit')){ ?>
				<a class="mtCreate button icon-pencil" title="Editer l'article" href="<?= $this->baseUrl("/auth/user/update/id/") ?>${iduser}"></a>
			<?php }?>
			<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('utilisateurs'),'delete')){ ?>
				<a class="button icon-cross blue-gradient delUser" title="Supprimer l'article" href="#" rel="${iduser}"></a>
			<?php }?>
		</span>
		<div class="low-padding align-center tiny-cell ">
		</div>
	</div>
</script>

<script  id="userIDClone" type="text/template">
	<div>
		<span class="hidden">${iduser}</span><input type="checkbox" class="userid" name="checked[]" id="check-${iduser}" value="${iduser}">
	</div>
</script>

<!------------------------ UserGroup Template ------------------------->


<script id="usergroupClone" type="text/template">
				<tr class="listenerCheckbox">
					<th scope="row" class="checkbox-cell hide-on-mobile"><span class="hidden">${usergroup.idgroup}</span><input type="checkbox" class="usergroupid" name="checked[]" id="check-${usergroup.idgroup}" value="${usergroup.idgroup}"></th>
					<td class="namegroup prop" entity="namegroup">${usergroup.namegroup}</td>
					{{if usergroup.statusgroup == true }}
						<td class="statusgroup hide-on-tablet prop" entity="statusgroup"><small class="tag">Actif</small></td>	
					{{else}}
						<td class="statusgroup hide-on-tablet prop " entity="statusgroup"><small class="tag red-bg">Inactif</small></td>	
					{{/if}}
					<td class="low-padding align-center tiny-cell border-right-action">
		                 <span class="button-group compact">
		                 		<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'edit')){ ?>
		             		    	<a class="mtCreate button icon-pencil" title="Editer l'utilisateur" href="<?= $this->baseUrl("/auth/usergroup/update/id/") ?>${usergroup.idgroup}"></a>
		             		   <?php }?>
		                      <?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'delete')){ ?>
		                       	<a class="button icon-cross blue-gradient delUsergroup" title="Supprimer l'utilisateur" href="#" rel="${usergroup.idgroup}"></a>
		                       <?php }?>
		                 </span>
		             </td>
				</tr>
</script>

<script id="usergroupActionClone" type="text/template">
	<div>
		<span class="button-group compact ">
			<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'edit')){ ?>
				<a class="mtCreate button icon-pencil" title="Editer l'article" href="<?= $this->baseUrl("/auth/usergroup/update/id/") ?>${idusergroup}"></a>
			<?php }?>
			<?php if(Zend_Registry::get('acl')->isAllowed(new Custom_Acl_UserRole(), new Custom_Acl_Resources('groupe'),'delete')){ ?>
				<a class="button icon-cross blue-gradient delUsergroup" title="Supprimer l'article" href="#" rel="${idusergroup}"></a>
			<?php }?>
		</span>
		<div class="low-padding align-center tiny-cell ">
		</div>
	</div>
</script>

<script  id="usergroupIDClone" type="text/template">
	<div>
		<span class="hidden">${idusergroup}</span><input type="checkbox" class="usergroupid" name="checked[]" id="check-${idusergroup}" value="${idusergroup}">
	</div>
</script>