<!--data table-->
<script
	src="<?=$this->baseUrl('resources_fo_ehcg/js/jquery.dataTables.js');?>"></script>
<script
	src="<?=$this->baseUrl('resources_fo_ehcg/js/dataTables.tableTools.js');?>"></script>
<script
	src="<?=$this->baseUrl('resources_fo_ehcg/js/jquery.dataTables.bootstrap.js');?>"></script>

<!-- Data table-->
<link rel="stylesheet" type="text/css"
	href="<?=$this->baseUrl('resources_fo_ehcg/css/libs/dataTables.fixedHeader.css');?>">
<link rel="stylesheet" type="text/css"
	href="<?=$this->baseUrl('resources_fo_ehcg/css/libs/dataTables.tableTools.css');?>">
<style>
::-webkit-scrollbar-track {
	-webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
	background-color: #6A6E9B;
}

::-webkit-scrollbar {
	width: 10px;
	background-color: #6A6E9B;
}

::-webkit-scrollbar-thumb {
	background-color: #1B9CDC;
	background-image: -webkit-gradient(linear, 0 0, 0 100%, color-stop(.5, rgba(255, 255, 255,
		.2)), color-stop(.5, transparent), to(transparent));
}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<header class="main-box-header clearfix">
				<!-- Breadcumbs -->
				<div class="row">
					<div class="col-md-6">
						<ul id="breadcrumbs-two">
							<li><a style="cursor: pointer;"><i class="fa fa-home"></i>
									Tableau de bord</a></li>

							<li><a class="current" style="cursor: pointer;"><i
									class="fa fa-files-o"></i> Gestion des utilisateurs</a></li>

						</ul>
					</div>
					<div class="col-md-6">
						<div class="pull-right">
							<button type="button" style="font-size: 12px;"
								id="btn_add_newUser" class="btn btn-success" onclick="location.href='/auth/user/add';">
								<i class="fa fa-plus-circle"></i> Nouveau utilisateur
							</button>
							
						</div>
					</div>
				</div>
			</header>
			<div class="main-box-body clearfix">
				<div class="col-md-12">
					<div class="table-responsive">
						<table id="table-clients" class="table table-hover user-list">
							<thead>
								<tr>
									<th>NOM</th>
									<th>PRENOM</th>
									<th>EMAIL</th>
									<th>LOGIN</th>
									<th>ROLE</th>
									<th>STATUS</th>
									<th>DATE CREATION</th>
									<th>ACTION</th>
								</tr>
							</thead>
							<tbody>
								<?php 
								
								foreach ($this->listeuser as $p):?>
								
								<tr>
									<td>
										<?=$p->lastname_user;?>
									</td>
									<td>
										<?=$p->firstname_user;?>
									</td>
									<td>
										<?=$p->email_user;?>
									</td>
									<td>
										<?=$p->login_user;?>
									</td>
									
									
									<td>
										<?php if($p->rank_user==0){echo "Opérateur";}else{echo "Administrateur";};?>
									</td>
									<td>
										<?php if($p->isActive_user==0){echo "Inactif";}else{echo "Actif";};?>
									</td>
									<td>
										<?=$p->dateregister_user;?>
									</td>
									<td><a href="/auth/user/edit/id/<?=$p->id_user?>"class="table-link"
										id="btn-edit-user-<?=$p->id_user;?>"
										style="cursor: pointer;"> <span class="fa-stack" title="Editer"> <i
												class="fa fa-square fa-stack-2x"></i> <i
												class="fa fa-pencil fa-stack-1x fa-inverse"></i>
										</span>
										
										</a>
										
								</td>
								</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	
	//DATATABE clients 
	table = $('#table-clients').dataTable({
		'info': false,
		 'oLanguage': {
	        sProcessing: "<i style='font-size:50px;color:#6A6E9B' class='fa fa-spinner fa-spin'></i> Chargement en cours ..."
	     },
	     'lengthMenu': [10,20,50,100],
	     "scrollY": "500px",
	     "jQueryUI": true,
		'sDom': 'lTfr<"clearfix">tip',
		'oTableTools': {
			'aButtons': []
                  } ,        
	   	  "paging": false,
	   	  "ordering":true,
	   	  "processing":true,
	   	  "searching":true
	});
	
		

});
</script>