<form id="<?=$this->form->getAttrib('id')?>" action="<?=$this->escape($this->form->getAction())?>">

<div class="modal-bg">
	<div class="modal-content custom-scroll" style="min-width: 200px; min-height: 170px; width: 520px; position: relative; max-width: 1511px; max-height: 266px;">
		<div class="standard-tabs same-height tabs-active tabs-animated tab-opened" style="height: 321px;">
			<ul class="tabs">
				<li class="active"><a href="#tab-prod1">Utilisateur</a></li>
			</ul>
			<div class="tabs-content" style="min-height: 29px;"><span class="tabs-back with-left-arrow top-bevel-on-light dark-text-bevel">Back</span>
		
				<div class="with-padding tab-active" id="tab-prod1" style="display: block; height: 279px;">
					<div class="button-height">
		            	
		                <div style="display:inline-block;width:100%;">
		                    <div style="width:48%;float:left;">
		                        <ul class="inputs">
		                            <li><span class="icon-user small-margin-right icon-size-2"></span><?= $this->form->lastnameuser->renderViewHelper(); ?></li>
		                            <li><span class="icon-user small-margin-right"></span><?= $this->form->firstnameuser->renderViewHelper(); ?></li>
		                            <li><span class="icon-mail small-margin-right"></span><?= $this->form->emailuser->renderViewHelper(); ?></li>
		                            <li><span class="icon-star small-margin-right"></span><?= $this->form->pwduser->renderViewHelper(); ?></li>
		                            <li><span class="icon-users"></span><?= $this->form->namegroup->renderViewHelper(); ?><?= $this->form->idgroup->renderViewHelper(); ?></li>
		                            <!--li><span class="icon-printer small-margin-right"></span><input type="text" name="customerFax" value="" class="input-unstyled" placeholder="Ligne fax" autocomplete="off" style="width:90%;"></li-->
		                        </ul>
		                        <span class="button-group">
		                    	<?php 
		                        $selectOptions = $this->form->isactiveuser->getMultiOptions();
		                        reset($selectOptions);
		                        $firstValue = key($selectOptions);
		                        foreach($selectOptions as $value => $label){
		                        ?>
		                        	<label for="isactiveuser-<?= $value; ?>" class="button blue-active tiny<?= ($value == $firstValue) ? ' active' : ''; ?>">
		                            <input type="radio" name="isactiveuser" id="isactiveuser-<?= $value; ?>" value="<?= $value; ?>"<?= ($value == $firstValue) ? ' checked="checked"' : ''; ?>>
		                            <?= $label ?>
			                        </label>                            
		                        <?php
		                        }
		                        ?>
	                		</span>
		                	</div>
		                    <div style="width:10px;"></div>
		                    <div style="width:48%;float:left;padding-left:10px;">
		                        <ul class="inputs">
		                        <li><span class="icon-mobile small-margin-right"></span><?= $this->form->mobileuser->renderViewHelper(); ?></li>
		                            <li><span class="icon-phone small-margin-right"></span><?= $this->form->phoneuser->renderViewHelper(); ?></li>
		                            <li><span class="icon-star small-margin-right"></span><?= $this->form->address1user->renderViewHelper(); ?></li>
		                            <li><span class="icon-star small-margin-right"></span><?= $this->form->zipuser->renderViewHelper(); ?></li>
		                            <li><span class="icon-star small-margin-right"></span><?= $this->form->cityuser->renderViewHelper(); ?></li>
		                            <li><span class="icon-star small-margin-right"></span><?= $this->form->countryuser->renderViewHelper(); ?></li>
		                        </ul>
		                    </div>
		                </div>
		                
		           </div>                                 
				</div>
				
			</div>
			
			<?= $this->form->iduser->renderViewHelper(); ?>
		</div>
	</div>
</div>

<div class="modal-buttons">
	<?= $this->form->submitUser->renderViewHelper(); ?>
</div>

</form>