<?php
// $this->form->setAction($this->url());
// echo $this->form;
?>
<section id="login-block">
	<div class="span4 offset4">
		<div class="signin">
			<h1 class="left-align-text">
				<b style="color: #00AEEF;">Mister</b> Devis </h1>
			<h3>
				<i style="font-size: 16px; color: #3d4990;">Votre outil de suivi des travaux projets</i>
				<br>
			</h3>
			<?php if ( $_SESSION['flash'] ): ?>
				<div class="alert alert-error ">
					<?= $_SESSION['flash'];
					$_SESSION['flash'] = null; ?>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			<?php endif; ?>
			<div class="block-content" id="block-content"></div>
			<div class="signin-wrapper" id="content-signin-wrapper">
				<h5 class="left-align-text">
					<b>Initialisation du mot de passe</b>
				</h5>
				<p class="p-ehcg" align="justify">Vous avez oublié votre mot de passe ? Pas de panique ! Indiquez-nous votre adresse email et Vous recevez un mot de passe temporaire que vous pouvez changer dans la
				                                  plateforme. Pensez à regarder dans votre dossier Spam si vous ne voyez pas arriver notre email.
				</p>
				<div class="content">
					<form id="password-form" name="password-form" action="/auth/login/forgotpassword" class="signin-wrapper" method="POST">
						<div class="form-horizontal no-margin well">
							<div class="control-group" style="margin-bottom: 0px;">
								<div class="control-label">
									<b>Adresse email</b>
								</div>
								<div class="controls" style="margin-left: 0px;">
									<input type="text" class="input input-block-level" name="email" id="email">
								</div>
							</div>
						</div>
						<div>&nbsp;</div>
						<div class="actions" style="padding: 0px 10px;">
							<input type="submit" class="btn btn-ehcg-entrer pull-right" value="Envoyer" id="btn-submit-mail">
							<span class="checkbox-wrapper"></span>
							<div class="clearfix"></div>
						
						</div>
					</form>
				</div>
				
				
				<div class="actions" style="padding: 5px 10px 16px;">
					<span class="checkbox-wrapper"><a href="/auth/login" class="pull-right">Se connecter</a>
					</span>
				</div>
			</div>
			<p align="right">© Mister Devis
				<script type="text/javascript">
					document.write(new Date().getFullYear());
				</script>
			</p>
		
		</div>
	</div>
</section>