<link href="<?= $this->baseUrl( 'resources_fo_ehcg/css/jquery.autocomplete.css' ); ?>" rel="stylesheet" type="text/css">
<link href="<?= $this->baseUrl( 'resources_fo_ehcg/css/selectize.css' ); ?>" rel="stylesheet" />
<link href="<?= $this->baseUrl( 'resources_fo_ehcg/css/selectize.bootstrap3.css' ); ?>" rel="stylesheet" type="text/css">
<style>
	#error-notif {
		color: red:
		display: none;
	}
	
	.form-group .help-block {
		display: none;
	}
	
	.form-group.has-error .help-block {
		display: block;
	}
	
	.list-activites .form-group, .list-departements .form-group {
		margin: 0;
	}
	
	a.remove-list-activites, a.remove-list-departements {
		margin-top: 20px;
		height: 32px;
	}
	
	#new-activity-btn, #new-departement-btn {
		margin-top: 20px;
		height: 32px;
	}
	
	.autocomplete-suggestion {
		padding: 4px 8px;
		cursor: pointer;
		border-bottom: 1px solid #CCC;
		-webkit-transition: background-color .4s;
		-moz-transition: background-color .4s;
		-ms-transition: background-color .4s;
		-o-transition: background-color .4s;
		transition: background-color .4s;
	}
	
	.autocomplete-suggestion:nth-child(odd) {
		background-color: #EEE;
	}
	
	.selectize-option {
		border-bottom: 1px solid #DDD;
	}
	
	.selectize-option:last-child {
		border-bottom: none
	}
	
	.selectize-control::before {
		-moz-transition: opacity 0.2s;
		-webkit-transition: opacity 0.2s;
		transition: opacity 0.2s;
		content: ' ';
		z-index: 2;
		position: absolute;
		display: block;
		top: 67%;
		right: 34px;
		width: 16px;
		height: 16px;
		margin: -8px 0 0 0;
		background: url(<?= $this->baseUrl( 'resources_fo_ehcg/img/spinner.gif'); ?>);
		background-size: 16px 16px;
		opacity: 0;
	}
	
	.selectize-control.loading::before {
		opacity: 0.4;
	}
	
	.selectize-control.multi .selectize-input > div {
		background-color: #1b9cdc;
		color: white;
		padding: 3px 10px;
		margin: 0 5px 5px 0;
	}
	
	.autocomplete-suggestion:hover {
		background-color: #DDD;
	}
	
	.autocomplete-suggestion small {
		display: block;
		font-size: 12px;
	}

</style>
<script type="text/javascript" src="<?= $this->baseUrl( 'resources_fo_ehcg/js/jquery.autocomplete.min.js' ); ?>"></script>

<div class="row">
	<div class="col-md-12">
		<div class="main-box clearfix">
			<header style="min-height: 0 !important;" class="main-box-header clearfix">
				<!-- Breadcumbs -->
				<div class="row">
					<div class="col-md-12">
						<ul id="breadcrumbs-two">
							<li>
								<a href="/<?= Zend_Registry::get( 'Zend_Locale' )->getLanguage(); ?>/fo/Job/dashboard">
									<i class="fa fa-home"></i>
									Tableau de bord</a></li>
							<li><a class="current" style="cursor: pointer;">
									<i class="fa fa-files-o"></i>
									Gestion des Artisans</a>
							</li>
						</ul>
					</div>
				</div>
				<!-- end breadcumbs -->
			</header>
			<div class="main-box-body clearfix">
				<form action="/auth/artisan/edit/id/<?= $this->id; ?>" method="POST" class="must-validate" novalidate>
					
					<div class="panel-group accordion" id="qualification-form">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#client-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Informations de l'artisan</a>
								</h4>
							</div>
							<div id="client-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body row">
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_artisan->nom_artisan; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->prenom_artisan; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->telephone_portable; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->telephone_fixe; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->fax; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->rcs; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->siret; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->code_NAF; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->horaireRDV; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->qualification; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_artisan->raison_sociale; ?>
											<?= $this->form->form_artisan->description; ?>
										</div>
										<div class="col-md-6">
											<div class="row list-activites">
												
												<label class="col-sm-12">Activites</label>
												<?php if ( $this->data['Artisan']['select_activites'] ): ?>
													
													<?php foreach ( $this->data['Artisan']['select_activites'] as $activite ): ?>
														<div class="activite-item">
															<div class="col-sm-11">
																<?= $this->form->form_artisan->select_activites
																	->setLabel( null )
																	->setValue( $activite ); ?>
															</div>
															<div class="col-sm-1">
																<a href="javascript:void(0)" class="btn btn-danger remove-list-activites">&times;</a>
															</div>
														</div>
													<?php endforeach; ?>
												
												<?php elseif ( $this->artisan ): ?>
													
													<?php foreach ( $this->artisan->activites as $activite ): ?>
														<div class="activite-item">
															<div class="col-sm-11">
																<?= $this->form->form_artisan->select_activites
																	->setLabel( null )
																	->setValue( $activite->id_activite ); ?>
															</div>
															<div class="col-sm-1">
																<a href="javascript:void(0)" class="btn btn-danger remove-list-activites">&times;</a>
															</div>
														</div>
													<?php endforeach; ?>
												
												<?php endif; ?>
												<div id="extra-activities"></div>
												<div class="col-sm-11">
													<?= $this->form->form_artisan->select_activites->setLabel( null )->setValue( '' ); ?>
												</div>
												<div class="col-sm-1">
													<a id="new-activity-btn" class="btn btn-primary">&plus;</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#address-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Adresse de l'artisan</a>
								</h4>
							</div>
							<div id="address-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body">
									<div class="panel panel-default row">
										<div class="col-md-12">
											<div class="col-md-6">
												<?= $this->form->form_artisan->adresse; ?>
											</div>
											<div class="col-md-6">
												<?= $this->form->form_artisan->adresse2; ?>
											</div>
										</div>
										
										<div class="col-md-12">
											<div class="col-md-6">
												<?= $this->form->form_artisan->code_postal ?>
											</div>
											<div class="col-md-6">
												<?= $this->form->form_artisan->ville ?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#address-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Zones d'activité</a>
								</h4>
							</div>
							<div id="address-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body">
									<div class="panel panel-default row">
										<div class="col-md-12">
											<div class="col-md-6">
												<div class="row list-departements">
													<label class="col-sm-12">
														<input type="radio" checked name="geolocalisation">
														Par departement
													</label>
													<div class="form-group" style="position: relative;">
														<select id="departemnts" class="form-control" multiple name="departements[]">
															<?php if ( $this->data['Artisan']['select_departement'] ): ?>
																
																<?php foreach ( $this->data['Artisan']['select_departement'] as $departement ): ?>
																	<option value="<?= $departement['code_departement']; ?>" selected><?= $departement['nom_departement']; ?></option>
																<?php endforeach; ?>
															
															<?php elseif ( $this->artisan ): ?>
																
																<?php foreach ( $this->artisan->departements as $departement ): ?>
																	<option value="<?= $departement->code_departement; ?>" selected><?= $departement->nom_departement ?></option>
																<?php endforeach; ?><?php endif; ?>
														</select>
													</div>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label>
														<input type="radio" name="geolocalisation" disabled />
														Géographique
													</label>
													<p style="text-align: center; font-size: 20px; padding: 15px; color: #CCC;">Coming soon</p>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#demande-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Informations d'identification</a>
								</h4>
							</div>
							<div id="demande-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body row">
									<div class="col-md-12">
										
										<div class="col-md-6">
											<?= $this->form->form_artisan->email_artisan; ?>
											<?= $this->form->form_artisan->login; ?>
										</div>
										
										<div class="col-md-6">
											<?= $this->form->form_artisan->pass; ?>
											<?= $this->form->form_artisan->pass2; ?>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="row" style="margin-top: 15px">
							<div class="col-md-12">
								<div class="pull-right">
									<span style="display: none; margin-right: 5px;" id="error-notif" class="text-danger"> Une erreur s'est produite, veuillez verifier les champs en rouge</span>
									<button class="btn btn-info" title="Sauvegarder les modifications" id="btn-save-edit-client" type="submit">
										<i class="fa fa-save"></i>
										Enregistrer
									</button>
								</div>
							</div>
						</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script src="<?= $this->baseUrl( 'resources_fo_ehcg/js/selectize.min.js' ); ?>"></script>
<script type="text/javascript">
	$(document).ready(function () {
		var email_artisan = $('#Artisan-email_artisan');
		var login = $('#Artisan-login');
		
		var code_postal = $('#Artisan-code_postal');
		var ville = $('#Artisan-ville');
		
		
		$('#departemnts').selectize({
			valueField: 'code_departement',
			labelField: 'nom_departement',
			searchField: ['nom_departement', 'code_departement'],
			sortField: 'nom_departement',
			create: false,
			render: {
				option: function (item, escape) {
					return '<div class="selectize-option"><span class="name">' + item.code_departement + ' - ' + item.nom_departement + '</span></div>'
				},
				item: function (item, escape) {
					return '<div class="selectize-option"><span class="name">' + item.code_departement + ' - ' + item.nom_departement + '</span></div>'
				}
			},
			closeAfterSelect: true,
			hideSelected: true,
			openOnFocus: false,
			selectOnTab: true,
			load: function (query, callback) {
				if (!query.length) return callback();
				$.ajax({
					url: '/auth/artisan/list-departements',
					data: {
						q: encodeURIComponent(query)
					},
					dataType: 'json',
					type: 'GET',
					error: function () {
						callback();
					},
					success: function (res) {
						console.log(res);
						callback(res.results.slice(0, 10));
					}
				});
			}
		});
		
		code_postal.autoComplete({
			minChars: 2,
			delay: 500,
			source: function (term, response) {
				$.getJSON('/auth/index/cities/', {q: term}, function (data) {
					response(data);
				});
			},
			renderItem: function (item) {
				return '<div class="autocomplete-suggestion" data-code="' + item.code + '"  data-ville="' + item.ville + '">' + item.ville + '<small>Code postal: ' + item.code + '</small></div>';
			},
			onSelect: function (e, term, item) {
				code_postal.val(item.data('code'));
				code_postal.parents('.form-group').removeClass('has-error');
				ville.val(item.data('ville'));
			}
		});
		
		
		ville.autoComplete({
			minChars: 2,
			delay: 500,
			source: function (term, response) {
				$.getJSON('/auth/index/cities/', {q: term}, function (data) {
					response(data);
				});
			},
			renderItem: function (item) {
				return '<div class="autocomplete-suggestion" data-code="' + item.code + '"  data-ville="' + item.ville + '">' + item.ville + '<small>Code postal: ' + item.code + '</small></div>';
			},
			onSelect: function (e, term, item) {
				ville.val(item.data('ville'));
				ville.parents('.form-group').removeClass('has-error');
				code_postal.val(item.data('code'));
			}
		});
		
		
		if (email_artisan.hasClass('has-error')) {
			email_artisan.next('.help-block').html('Cette adresse email exite déjà');
			email_artisan.parents('.form-group').addClass('has-error');
			email_artisan.focus();
		}
		if (login.hasClass('has-error')) {
			login.next('.help-block').html('Ce login exite déjà');
			login.parents('.form-group').addClass('has-error');
			login.focus();
		}
		
		
		$('form input').on('keydown keypress', function (e) {
			var code = e.keyCode || e.which;
			if (code === 13) return false;
		});
		
		$('.must-validate').submit(function () {
			var isValid = true;
			$(this).find('[required]').each(function () {
				
				if (!$(this).val() || $(this).val().trim().length === 0) {
					$(this).data('dirty', true);
					$(this).parents('.form-group').addClass('has-error');
					$(this).parents('.form-group').find('.help-block').show();
					$(this).focus();
					isValid = false;
				} else {
					$(this).parents('.form-group').removeClass('has-error');
					$(this).parents('.form-group').find('.help-block').hide();
				}
			});
			
			if (!isValid) $('#error-notif').show();
			else $('#error-notif').hide();
			return isValid;
		});
		
		$('[required]').on('blur', function () {
			$(this).data('dirty', true);
			if (!$(this).val() || $(this).val().trim().length === 0) {
				$(this).parents('.form-group').addClass('has-error');
				$(this).parents('.form-group').find('.help-block').show();
			} else {
				$(this).parents('.form-group').removeClass('has-error');
				$(this).parents('.form-group').find('.help-block').hide();
			}
		}).on('keyup', function () {
			if (!$(this).data('dirty')) return;
			if (!$(this).val() || $(this).val().trim().length === 0) {
				$(this).parents('.form-group').addClass('has-error');
				$(this).parents('.form-group').find('.help-block').show();
			} else {
				$(this).parents('.form-group').removeClass('has-error');
				$(this).parents('.form-group').find('.help-block').hide();
			}
		});
		
		$('#new-activity-btn').on('click', function () {
			var url = '/auth/artisan/new-activite';
			$.ajax({
				url: url,
				method: 'GET',
				dataType: 'json',
				success: function (data) {
					if (data.error === 0)
						$('#extra-activities').append(data.html);
				}
			});
		}).change();
		
		// $('#new-departement-btn').on('click', function () {
		// 	var url = '/auth/artisan/new-departement';
		// 	$.ajax({
		// 		url: url,
		// 		method: 'GET',
		// 		dataType: 'json',
		// 		success: function (data) {
		// 			if (data.error === 0)
		// 				$('#extra-departements').append(data.html);
		// 		}
		// 	});
		// }).change();
		
		$(document).on('click', '.remove-list-activites', function () {
			$(this).parents('.activite-item').remove();
		});
		
		// $(document).on('click', '.remove-list-departements', function () {
		// 	$(this).parents('.departement-item').remove();
		// });
	});
</script>
