<div class="form-group">
    <label for="TYPE_DIFFUSION_CHALEUR">Type diffusion de chaleur :</label>
    <select class="form-control" name="TYPE_DIFFUSION_CHALEUR" id="TYPE_DIFFUSION_CHALEUR">
        <option <?= $this->qualification->type_diffusion_chaleur === 'Radiateur à eau' ? 'selected' : null; ?>  value="Radiateur à eau">Radiateur à eau</option>
        <option <?= $this->qualification->type_diffusion_chaleur === 'Plancher Chauffant' ? 'selected' : null; ?>  value="Plancher Chauffant">Plancher Chauffant</option>
        <option <?= $this->qualification->type_diffusion_chaleur === 'Je ne sais pas' ? 'selected' : null; ?>  value="Je ne sais pas">Je ne sais pas</option>
    </select>
</div>