<div class="form-group">
    <label for="">Type d'installation :</label>
    <select class="form-control" name="TYPE_INSTALLATION" id="TYPE_INSTALLATION">
        <option <?= $this->qualification->type_installation  === 'Chauffage à Bois' ? 'selected' : null; ?> value="Chauffage à Bois">Chauffage à Bois</option>
        <option <?= $this->qualification->type_installation  === 'Poêle à Granules' ? 'selected' : null; ?> value="Poêle à Granules">Poêle à Granules</option>
        <option <?= $this->qualification->type_installation  === 'Chaudière à Granules' ? 'selected' : null; ?> value="Chaudière à Granules">Chaudière à Granules</option>
    </select>
</div>


<div class="form-group">
    <label for="CONDUITE_FUMEE">Conduite fumée :</label>
    <select class="form-control" name="CONDUITE_FUMEE" id="CONDUITE_FUMEE">
        <option <?= $this->qualification->conduite_fumee  === 'Déjà posé' ? 'selected' : null; ?> value="Déjà posé">Déjà posé</option>
        <option <?= $this->qualification->conduite_fumee  === 'Pas encore posé' ? 'selected' : null; ?> value="Pas encore posé">Pas encore posé</option>
        <option <?= $this->qualification->conduite_fumee  === 'A remplacer' ? 'selected' : null; ?> value="A remplacer">A remplacer</option>
        <option <?= $this->qualification->conduite_fumee  === 'A réparer' ? 'selected' : null; ?> value="A réparer">A réparer</option>
        <option <?= $this->qualification->conduite_fumee  === 'A nettoyer' ? 'selected' : null; ?> value="A nettoyer">A nettoyer</option>
    </select>
</div>