<div style="width: 650px; margin: 80px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center;">Une nouvelle demande</h1>
	<p>Bonjour <?= $this->operateur->firstname_user ?> <?= $this->operateur->lastname_user ?>,</p>
	<p>Nous vous confirmons la réception de votre demande de devis.</p>
	<p>Prochainement un de nos conseillers vous contactera afin de recueillir l'ensemble des informations concernant votre projet.</p>
	<h1>Demande N°: <?= $this->ref; ?></h1>
	<p><a href="<?= $this->demande_url; ?>">Cliquez ici pour accèder au backoffice</a></p>
	<p> A très bientôt</p>
	<p>L'équipe <a href="http://mister-devis.com">mister-devis.com</a></p>
</div>