<div style="width: 650px; margin: 80px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center;">Une nouvelle demande</h1>
	<p>Bonjour <?= $this->artisan->nom_artisan ?> <?= $this->artisan->prenom_artisan ?>,</p>
	<p>Vous venez de vous inscrire sur notre site mister-devis.com et nous sommes ravis de vous compter parmi nos membres.</p>
	<p>Voici vos identifiants :</p>
	
	<p>Nom d'utilisateur : <strong><?= $this->artisan->login; ?></strong></p>
	<p>Mot de passe : <strong><?= $this->pass; ?></strong></p>
	
	<p>Nous vous remercions de votre confiance et nous vous souhaitons la bienvenue.</p>
	<p>Prochainement un de nos conseillers vous contactera afin de recueillir l'ensemble des informations concernant votre activité.</p>
	<p>Contactez-nous au plus vite au 09 88 77 27 00 ou par mail à <a href="mailto:t.kapplan@mister-devis.com">t.kapplan@mister-devis.com</a></p>
	<p> A très bientôt</p>
	<p></p>
	<p>Thomas Kapplan<br>09.88.77.27.00<br><a href="mailto:t.kapplan@mister-devis.com">t.kapplan@mister-devis.com</a></p>
</div>