<div style="width: 650px; margin: 80px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center;">Une nouvelle demande</h1>
	<p>Bonjour <?= $this->particulier->prenom_particulier ?> <?= $this->particulier->nom_particulier ?>,</p>
	<p>lorem ipsum dolor sit amet consectetur adipiscing elit. aenean ac interdum nisi.</p>
	<p>Aenean interdum lorem dolor adipiscing elit.</p>
	<h1>Demande N°: <?= $this->ref; ?></h1>
	<p><a href="<?= $this->demande_url; ?>">Cliquez ici pour accèder au backoffice</a></p>
	<p> A très bientôt</p>
	<p>L'équipe <a href="http://mister-devis.com">mister-devis.com</a></p>
</div>