<style>
	#error-notif {
		color: red:
		display: none;
	}

	.form-group .help-block {
		display: none;
	}

	.form-group.has-error .help-block {
		display: block;
	}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="main-box clearfix">
			<header style="min-height: 0 !important;" class="main-box-header clearfix">
				<!-- Breadcumbs -->
				<div class="row">
					<div class="col-md-12">
						<ul id="breadcrumbs-two">
							<li>
								<a href="/<?= Zend_Registry::get('Zend_Locale')->getLanguage(); ?>/fo/Job/dashboard">
									<i class="fa fa-home"></i>
									Tableau de bord</a></li>
							<li><a class="current" style="cursor: pointer;">
									<i class="fa fa-files-o"></i>
									Qualification Salle de Bain</a>
							</li>
						</ul>
					</div>
				</div>
				<!-- end breadcumbs -->
			</header>
			<div class="main-box-body clearfix">
				<form action="/auth/sallebain/edit/id/<?= $this->id; ?>" method="POST" class="must-validate" novalidate>
					
					<div class="panel-group accordion" id="qualification-form">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#client-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Informations du client</a>
								</h4>
							</div>
							<div id="client-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body row">
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_particulier->civilite; ?>
										</div>
									</div>
									
									<div class="col-md-12">
										
										<div class="col-md-6">
											<?= $this->form->form_particulier->nom_particulier; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_particulier->prenom_particulier; ?>
										</div>
									</div>
									
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_demande->type_demandeur; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_demande->type_propriete; ?>
										</div>
									</div>
									
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_particulier->telephone_portable; ?>

										</div>
										<div class="col-md-6">
											<?= $this->form->form_particulier->telephone_fixe; ?>

										</div>
									</div>
									
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_particulier->email; ?>

										</div>
										<div class="col-md-6">
											<?= $this->form->form_particulier->horaireRDV; ?>

										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#demande-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Informations de la demande</a>
								</h4>
							</div>
							<div id="demande-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body row">
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_demande->titre_demande; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_demande->delai_souhaite; ?>
										</div>

									</div>
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_demande->objectif_demande; ?>
										</div>
										<div class="col-md-6">
											<?= $this->form->form_demande->financement_projet; ?>
										</div>

									</div>
									<div class="col-md-12">
										<div class="col-md-6">
											<?= $this->form->form_demande->prestation_souhaite; ?>
											<?= $this->form->form_demande->description; ?>
										</div>
										<div class="col-md-6">

											<?= $this->form->form_demande->budget_approximatif; ?>
											<?= $this->form->form_demande->qualification; ?>
										</div>

									</div>
								</div>
							</div>
						</div>
						
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#qualif-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Qualification</a>
								</h4>
							</div>
							<div id="qualif-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body">
									<div class="col-md-6">
										<?= $this->form->form_qualif->type_travaux; ?>
										<?= $this->form->form_qualif->equipement_futur_salle; ?>
										<?= $this->form->form_qualif->surface_au_sol; ?>
										<?= $this->form->form_qualif->depose_ancienne_salle; ?>
										<?= $this->form->form_qualif->travaux_plomberie; ?>
										<?= $this->form->form_qualif->niveau_gamme; ?>
										<?= $this->form->form_demande->indication_complementaire; ?>
									</div>
									<div class="col-md-6">
										<?= $this->form->form_demande->type_batiment; ?>
										<?= $this->form->form_qualif->travaux_electrecite; ?>
										<?= $this->form->form_qualif->travaux_revetement; ?>
										<?= $this->form->form_qualif->travaux_peinture; ?>
										<?= $this->form->form_qualif->travaux_plomberie; ?>
										<?= $this->form->form_qualif->meuble_rengement; ?>
										<?= $this->form->form_qualif->hauteur_sous_plafond; ?>
									</div>
								</div>
							</div>
						</div>
						
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#address-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Adresse du chantier</a>
								</h4>
							</div>
							<div id="address-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body">
									<div class="panel panel-default row">
										<div class="col-md-12">
											<div class="col-md-6">
												<?= $this->form->form_chantier->adresse; ?>
											</div>
											<div class="col-md-6">
												<?= $this->form->form_chantier->adresse2; ?>
											</div>
										</div>
										
										<div class="col-md-12">
											<div class="col-md-6">
												<?= $this->form->form_chantier->ville; ?>
											</div>
											<div class="col-md-6">
												<?= $this->form->form_chantier->code_postal ?>
											</div>
										</div>
										<div class="col-md-12">
											<div class="col-md-6">
												<?= $this->form->form_chantier->id_zone; ?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a class="accordion-toggle" data-toggle="collapse" data-parent="#qualification-form" href="#online-info-collapse">
										<i class="fa fa-file-text-o"></i>
										Qualification</a>
								</h4>
							</div>
							<div id="online-info-collapse" class="panel-collapse collapse in">
								<div class="panel-body">
									<div class="col-md-6">
										<?= $this->form->form_demande->prix_mise_en_ligne; ?>
										<?= $this->form->form_demande->prix_promo; ?>
									</div>
									<div class="col-md-6">
										<?= $this->form->form_demande->publier_en_ligne; ?>
									</div>
								</div>
							</div>
						</div>
						
						<div class="row" style="margin-top: 15px">
							<div class="col-md-12">
								<div class="pull-right">
									<span style="display: none; margin-right: 5px;" id="error-notif" class="text-danger"> Une erreur s'est produite, veuillez verifier les champs en rouge</span>
									<button class="btn btn-info" type="submit">
										<i class="fa fa-save"></i>
										Enregistrer
									</button>
								</div>
							
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function () {
		$('.must-validate').submit(function () {
			var isValid = true;
			$(this).find('[required]').each(function () {
				
				if (!$(this).val() || $(this).val().trim().length === 0) {
					$(this).data('dirty', true);
					$(this).parents('.form-group').addClass('has-error');
					$(this).parents('.form-group').find('.help-block').show();
					$(this).focus();
					isValid = false;
				} else {
					$(this).parents('.form-group').removeClass('has-error');
					$(this).parents('.form-group').find('.help-block').hide();
				}
			});
			if (!isValid) $('#error-notif').show();
			else $('#error-notif').hide();
			return isValid;
		});

		$('[required]').on('blur', function () {
			$(this).data('dirty', true);
			if (!$(this).val() || $(this).val().trim().length === 0) {
				$(this).parents('.form-group').addClass('has-error');
				$(this).parents('.form-group').find('.help-block')
					.html('Ce champs est oubligatoire')
					.show();
			} else {
				$(this).parents('.form-group').removeClass('has-error');
				$(this).parents('.form-group').find('.help-block').html('').hide();
			}
		}).on('keyup', function () {
			if (!$(this).data('dirty')) return;
			if (!$(this).val() || $(this).val().trim().length === 0) {
				$(this).parents('.form-group').addClass('has-error');
				$(this).parents('.form-group').find('.help-block').show();
			} else {
				$(this).parents('.form-group').removeClass('has-error');
				$(this).parents('.form-group').find('.help-block').hide();
			}
		});
	});
</script>
