<!DOCTYPE html>
<html lang="en">
<head>

	<title>BAT Administration</title>
	<meta charset="utf-8">
	
	<!-- Global stylesheets -->
	<link href="<?=$this->baseUrl('resources_bo/css/reset.css');?>" rel="stylesheet" type="text/css">
	<link href="<?=$this->baseUrl('resources_bo/css/common.css');?>" rel="stylesheet" type="text/css">
	<link href="<?=$this->baseUrl('resources_bo/css/form.css');?>" rel="stylesheet" type="text/css">
	<link href="<?=$this->baseUrl('resources_bo/css/standard.css');?>" rel="stylesheet" type="text/css">
	<link href="<?=$this->baseUrl('resources_bo/css/special-pages.css');?>" rel="stylesheet" type="text/css">

	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
	<link rel="icon" type="image/png" href="favicon-large.png">
	
	<!-- Generic libs -->
	<script type="text/javascript" src="<?=$this->baseUrl('resources_bo/js/html5.js');?>"></script><!-- this has to be loaded before anything else -->
	<script type="text/javascript" src="<?=$this->baseUrl('resources_bo/js/jquery-1.4.2.min.js');?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('resources_bo/js/old-browsers.js');?>"></script>		<!-- remove if you do not need older browsers detection -->
	
	<!-- Template core functions -->
	<script type="text/javascript" src="<?=$this->baseUrl('resources_bo/js/common.js');?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('resources_bo/js/standard.js');?>"></script>
	<!--[if lte IE 8]><script type="text/javascript" src="<?=$this->baseUrl('resources_bo/js/standard.ie.js');?>"></script><![endif]-->
	<script type="text/javascript" src="<?=$this->baseUrl('resources_bo/js/jquery.tip.js');?>"></script>
	

	
	
	
</head>

<!-- the 'special-page' class is only an identifier for scripts -->
<body class="special-page login-bg dark">
<?= $this->layout()->content; ?>
</body>
</html>