<table style="background:rgba(128,128,128,0.02)" width="100%" cellspacing="0" cellpadding="0" border="0">
          <tbody>
            <tr>
              <td>
                <table  align="center" width="600" cellspacing="0" cellpadding="0" border="0">
                  <tbody>
                    <tr>
                      <td>
                        <div>
                          <table style="background:rgba(128,128,128,0.02)" align="center" width="600" cellspacing="0" cellpadding="0" border="0">
                            <tbody>
                              <tr>
                                <td width="200"><br>
                                </td>
                                <td width="200"><br>
                                </td>
                                <td width="200"><br>
                                </td>
                              </tr>
                              <tr>
                                <td width="190"><br>
                                </td>
                                <td align="center" width="200" valign="top"><img src="logo_mister_devis-1.png" alt="Mister-devis.com" width="247" height="50" class="CToWUd"></td>
                                <td width="200"><br>
                                </td>
                              </tr>
                              <tr>
                                <td width="200"><br>
                                </td>
                                <td width="200"><br>
                                </td>
                                <td width="200"><br>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <div>
                          <table align="center" width="600" cellspacing="0" cellpadding="0" border="0">
                            <tbody>
                              <tr>
                                <td style="padding:36px 48px;background-color:#0184c2;color:#ffffff" colspan="4" align="center" width="500">
                                  <h1 class="m_2322405772741087723m_104912678704188478bigtitle">
                                    Votre demande de devis est publiée en ligne</h1>
                                </td>
                              </tr>
                              <tr>
                                <td style="padding-top:5px;padding-left:20px;padding-right:20px" colspan="4">
                                  <div>
                                    <p>
                                      Bonjour,</p>
                                    <p>
                                      Nous vous informons que votre demande de devis est publiée en ligne. 
									</p>
                                    <p>
                                      les artisans de notre plateforme vont vous contacter si ça entre de leur intérêt.</p>
                                    <h2>
                                      Demande N°: PSC-1281:</h2>
                                  </div>
                                  <div>
                                    &nbsp;<i>A très bientôt</i></div>
                                  <div>
                                    <p>
                                      L'équipe <a href="http://mister-devis.com" target="_blank">mister-devis.com</a></p>
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td style="padding:0 48px 48px 48px;border:0;color:#0184c2;font-family:Arial;font-size:12px;line-height:125%;text-align:center" colspan="4" valign="middle">
                                  <br>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>